### ISSUE TITLE
gtk treeview expansion

### ISSUE THREAD

**Issue by Behrooz-Amoozad** [NSinopoli/newcash-prototype#1]
I think this is a different project from the one mentioned in https://groups.google.com/forum/#!msg/voidlinux/sJbLR_STlDo/iTrMxfSpHgAJ
And I'm not sure If this is the right place to ask this but I'm asking anyway.
Were you able to solve the issue? I'm experiencing the same problem on multiple(all of them) windows machines and reading the source code of the function drawing the arrows I beleive it used cairo or some other grphics library and there are no fonts/images involved. That's as far as I went. If you were able to dug up anything else that you can remember after 2 years I'd be really thankful if you could share them with me.

**Comment by NSinopoli** [comment]
Hi @Behrooz-Amoozad. As you've guessed, this is a totally different project from the one mentioned on that forum. Sorry I can't be of any help.
